services:
  db:
    image: postgres:15
    container_name: cofbase
    restart: always
    environment:
      POSTGRES_USER: selin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: buildcof
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

